language: java
jdk:
  - openjdk8
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.gradle/

# We depend on a WildFly deployment for some of the production
# .jar files. Download it and install just above our repo.
before_script:
  - wget http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz -O /tmp/wildfly-10.1.0.Final.tar.gz
  - pushd ..
  - tar -xvf /tmp/wildfly-10.1.0.Final.tar.gz
  - popd

install: true

# The build step here also builds our Javadocs.
script:
  - cd psm-app
  - ./gradlew --no-daemon --console=plain clean cms-portal-services:build
  - ../scripts/start-wildfly-deploy-application.sh
  - ./gradlew --no-daemon --console=plain clean build cms-web:apiDocs


# Push the new Javadocs to our GitHub Pages site.
after_success:
  - ../scripts/push-javadoc-to-gh-pages.sh
  
