# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Source Provider Screening Module (PSM)
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The PSM project seeks to develop a cohesive, free, open-source
  provider screening module for states to use in developing a
  modern, modular Medicaid IT system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://providerscreeningmodule.org" # the base hostname & protocol for your site
twitter_username: project_psm

# Build settings
markdown: kramdown
